name: fouta_app
description: "Fouta social media application"
publish_to: 'none'
version: 2.1.1+12

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Localization support for English and French.
  flutter_localizations:
    sdk: flutter
  # Version 0.20.x is required by flutter_localizations from the Flutter SDK.
  intl: ^0.20.2
  # Persist simple settings such as theme preference.
  shared_preferences: ^2.2.2
  # Core Firebase packages used by Fouta.
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  firebase_messaging: ^14.9.0
  # State management and connectivity.
  provider: ^6.1.2
  connectivity_plus: ^6.0.3
  # Miscellaneous packages from the existing project.
  http: ^1.2.1
  path_provider: ^2.1.3
  cached_network_image: ^3.3.1
  flutter_blurhash: ^0.9.1
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.6
  cupertino_icons: ^1.0.6
  badges: ^3.1.2
  image_picker: ^1.1.2
  camera: ^0.10.5+2
  visibility_detector: ^0.4.0+2
  permission_handler: ^11.3.0
  # Update to the latest record plugin so its platform implementations,
  # including Linux, align with the current platform interface and expose
  # `startStream`.
  record: ^5.1.1
  photo_view: ^0.14.0
  video_player: ^2.8.2
  subtitle_wrapper_package: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

dependency_overrides:

  # Ensure the Linux implementation matches the latest record API.
  record_linux: ^1.0.0


flutter:
  uses-material-design: true
  # Enable Flutter's l10n tool to generate localization classes from ARB files.
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_24pt-Regular.ttf
        - asset: assets/fonts/Inter_24pt-Bold.ttf
          weight: 700

# Configuration for the flutter_launcher_icons plugin.  This section must be
# placed at the top level of the pubspec (not under the `flutter:` block).
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/fouta_logo_transparent.png"
