// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcZLsw9mEiVIAll74KYE4nzGoZSS1C5eo',
    appId: '1:530812811944:web:052e8350fe57c519d2a09d',
    messagingSenderId: '530812811944',
    projectId: 'fouta-app',
    authDomain: 'fouta-app.firebaseapp.com',
    storageBucket: 'fouta-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfSF2IyJT7T9QODoPwUPsj2vP9Tx2qYaQ',
    appId: '1:530812811944:android:25dbfdf862b9a26fd2a09d',
    messagingSenderId: '530812811944',
    projectId: 'fouta-app',
    storageBucket: 'fouta-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs1ZyHp3Zs3St_hRrCTjy0cDyGabSh-Lw',
    appId: '1:530812811944:ios:9580f01b27f859eed2a09d',
    messagingSenderId: '530812811944',
    projectId: 'fouta-app',
    storageBucket: 'fouta-app.firebasestorage.app',
    iosBundleId: 'com.example.foutaApp',
  );
}
