platform :ios, '12.0'
# Load Flutter’s CocoaPods helper script from the SDK
load File.join('/Users/Momo/Developer/flutter', 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods
end

post_install do |installer|
  if defined?(flutter_post_install)
    flutter_post_install(installer)
  else
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
    end
  end
end



