# Copyright 2014 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

ENV['COCOAPODS_DISABLE_DART_SUBPROCESS'] = 'true'

$flutter_minimum_ios_version_plugins = {}

load File.join(File.dirname(File.realpath(__FILE__)), '..', 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  flutter_post_install(installer)
  # --- Start Fouta Patch: Remove -G Flag ---
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['OTHER_CFLAGS']&.delete('-G')
    end
  end
  # --- End Fouta Patch ---
end