# This file goes in .github/workflows/build.yml

name: Build Fouta iOS App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Verify Flutter environment
      run: flutter doctor

    - name: Get dependencies
      run: flutter pub get

    - name: Import Apple Code Signing
      # THE FIX IS HERE: Changed @v2 to @v1
      uses: apple-actions/import-codesigning-certs@v1
      with:
        p12-file-base64: ${{ secrets.APPLE_CERTIFICATE_BASE64 }}
        p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        provisioning-profile-base64: ${{ secrets.APPLE_PROVISIONING_PROFILE_BASE64 }}

    - name: Build iOS App
      run: flutter build ipa --release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: FoutaApp-iOS
        path: build/ios/ipa/*.ipa