name: Firebase Deploy (rules, indexes, functions)

on:
  push:
    branches: [ dev ]
    paths:
      - "firestore.rules"
      - "firestore.indexes.json"
      - "storage.rules"
      - "functions/**"
      - "firebase.json"
      - ".firebaserc"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # required by google-github-actions/auth

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Select project
        run: firebase use ${{ secrets.FIREBASE_PROJECT_ID }} --project ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Validate rules + indexes (best-effort)
        run: |
          firebase emulators:exec --project ${{ secrets.FIREBASE_PROJECT_ID }} --only firestore "echo OK" || true

      - name: Deploy rules & indexes
        run: |
          firebase deploy --non-interactive \
            --only firestore:rules,firestore:indexes,storage:rules \
            --project ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Deploy functions (if present)
        run: |
          if [ -d "functions" ]; then
            npm --prefix functions ci
            firebase deploy --non-interactive --only functions --project ${{ secrets.FIREBASE_PROJECT_ID }}
          else
            echo "No functions dir; skipping"
          fi

