name: Validation
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter doctor -v
      - name: Run duplicate check and pub get
        run: |
          chmod +x scripts/validate.sh
          bash scripts/validate.sh
